/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.svgpath.ui.contentassist;

import at.bestsolution.efxclipse.tooling.svgpath.ui.contentassist.AbstractSvgPathProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SvgPathProposalProvider extends AbstractSvgPathProposalProvider {

}
