/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.fxmlx.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.bestsolution.efxclipse.tooling.fxmlx.services.FXMLDslGrammarAccess;

public class FXMLDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FXMLDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_ML_COMMENT", "RULE_WS");
	}
	
	@Override
	protected at.bestsolution.efxclipse.tooling.fxmlx.parser.antlr.internal.InternalFXMLDslParser createParser(XtextTokenStream stream) {
		return new at.bestsolution.efxclipse.tooling.fxmlx.parser.antlr.internal.InternalFXMLDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "FXML";
	}
	
	public FXMLDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FXMLDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
