/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.svgpath;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SvgPathUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.bestsolution.efxclipse.tooling.svgpath.ui.internal.SvgPathActivator.getInstance().getInjector("at.bestsolution.efxclipse.tooling.svgpath.SvgPath");
	}
	
}
