<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fXMLDsl" nsURI="http://www.bestsolution.at/efxclipse/tooling/fxmlx/FXMLDsl"
    nsPrefix="fXMLDsl">
  <eClassifiers xsi:type="ecore:EClass" name="FXML">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xmlDec" eType="#//XMLDec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingInstructions"
        upperBound="-1" eType="#//ProcessingInstruction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootElement" eType="#//ElementDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLDec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="props" upperBound="-1"
        eType="#//AttributePropertyDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingInstruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerElementDefinition" eSuperTypes="#//ElementDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//AttributePropertyDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//PCData"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ElementDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endnamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyElementDefinition" eSuperTypes="#//ElementDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="props" upperBound="-1"
        eType="#//AttributePropertyDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributePropertyDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
