/*
 * generated by Xtext
 */
package at.bestsolution.efxclipse.tooling.fxmlx.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.common.types.xtext.ui.ITypesProposalProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import at.bestsolution.efxclipse.tooling.fxmlx.ui.contentassist.ImportingTypesProposalProvider;
import at.bestsolution.efxclipse.tooling.fxmlx.ui.labeling.FXMLDslHighlightingCalculator;
import at.bestsolution.efxclipse.tooling.fxmlx.ui.labeling.FXMLDslHighlightingConfiguration;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FXMLDslUiModule extends at.bestsolution.efxclipse.tooling.fxmlx.ui.AbstractFXMLDslUiModule {
	public FXMLDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(ISemanticHighlightingCalculator.class).to(FXMLDslHighlightingCalculator.class);
		binder.bind(IHighlightingConfiguration.class).to(FXMLDslHighlightingConfiguration.class);
	}
	
	@Override
	public Class<? extends ITypesProposalProvider> bindITypesProposalProvider() {
		return ImportingTypesProposalProvider.class;
	}
}
