/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.fxgraph.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.bestsolution.efxclipse.tooling.fxgraph.services.FXGraphGrammarAccess;

public class FXGraphParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FXGraphGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.bestsolution.efxclipse.tooling.fxgraph.parser.antlr.internal.InternalFXGraphParser createParser(XtextTokenStream stream) {
		return new at.bestsolution.efxclipse.tooling.fxgraph.parser.antlr.internal.InternalFXGraphParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public FXGraphGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FXGraphGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
