/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.svgpath.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SvgPathAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/bestsolution/efxclipse/tooling/svgpath/parser/antlr/internal/InternalSvgPath.tokens");
	}
}
