<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="photoedit" nsURI="http://efxclipse.org/examples/photoedit/v1.0"
    nsPrefix="photoedit">
  <eClassifiers xsi:type="ecore:EClass" name="BaseObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhotoEditApp" eSuperTypes="#//BaseObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albums" upperBound="-1"
        eType="#//Album" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Album" eSuperTypes="#//BaseObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="media" upperBound="-1"
        eType="#//Media" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverImage" eType="#//Photo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Media" abstract="true" eSuperTypes="#//BaseObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Photo" eSuperTypes="#//Media">
    <eStructuralFeatures xsi:type="ecore:EReference" name="areas" upperBound="-1"
        eType="#//PhotoArea" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Source"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhotoArea" eSuperTypes="#//BaseObject">
    <eOperations name="contains" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source" abstract="true" eSuperTypes="#//BaseObject">
    <eOperations name="getPreviewObjectStream" eType="#//InputStream"/>
    <eOperations name="getObjectStream" eType="#//InputStream"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinarySource" eSuperTypes="#//Source">
    <eStructuralFeatures xsi:type="ecore:EReference" name="previewObject" eType="#//BinaryObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="#//BinaryObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URLSource" eSuperTypes="#//Source">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="previewObjectURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryObject" eSuperTypes="#//BaseObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="InputStream" instanceClassName="java.io.InputStream"/>
</ecore:EPackage>
