<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="photoedit" nsURI="http://efxclipse.org/examples/photoedit/v1.0"
    nsPrefix="photoedit">
  <eClassifiers xsi:type="ecore:EClass" name="PhotoEditApp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albums" upperBound="-1"
        eType="#//Album" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Album">
    <eStructuralFeatures xsi:type="ecore:EReference" name="media" upperBound="-1"
        eType="#//Media"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Media" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Photo" eSuperTypes="#//Media">
    <eStructuralFeatures xsi:type="ecore:EReference" name="areas" upperBound="-1"
        eType="#//PhotoArea"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhotoArea">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source" abstract="true">
    <eOperations name="getPreviewObjectStream" eType="#//InputStream"/>
    <eOperations name="getObjectStream" eType="#//InputStream"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinarySource" eSuperTypes="#//Source">
    <eStructuralFeatures xsi:type="ecore:EReference" name="previewObject" eType="#//BinaryObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="#//BinaryObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="InputStream" instanceClassName="java.io.InputStream"/>
</ecore:EPackage>
