/*
 * generated by Xtext
 */
package at.bestsolution.efxclipse.tooling.fxgraph.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FXGraphUiModule extends at.bestsolution.efxclipse.tooling.fxgraph.ui.AbstractFXGraphUiModule {
	public FXGraphUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
